### ISSUE TITLE
How jRakNet works with RakNet?

### ISSUE THREAD

**Issue by shuizhihun** [GoMint/jRakNet#3]
We're working on a game, We're going to use RakNet on the client side, if we use jRakNet on the server side, What we need to do to make it work? other Suggestions? Thanks!

**Comment by geNAZt** [comment]
Hi, jRaknet should work with normal raknet just fine. The modifications made to the Raknet Protocol are only in the unconnected ping/pong system which need to be enabled with #setMojangModificationEnabled(true) in the Client/ServerSocket. 

To use the server socket for example you have to build / bind it like this:

```java
this.socket = new ServerSocket( maxConnections < 0 ? 20 : maxConnections );
this.socket.setEventLoopFactory( this.server.getThreadFactory() );
this.socket.setEventHandler( new SocketEventHandler() {
            @Override
            public void onSocketEvent( Socket socket, SocketEvent socketEvent ) {
                // Custom events
            }
        } );
 this.socket.bind( host, port );
```

The SocketEvents are this:

        NEW_INCOMING_CONNECTION,
        CONNECTION_CLOSED,
        CONNECTION_DISCONNECTED,
        UNCONNECTED_PONG,
        CONNECTION_ATTEMPT_FAILED,
        CONNECTION_ATTEMPT_SUCCEEDED,
        UNCONNECTED_PING

I guess you can tell by the names of the event types when they arrive at the handler.

After you have bound the socket you should be able to ping the Raknet System. To get custom Encapsulated Packets you need to poll the system in intervals.

To accept connections:
```java
private List<Connection> raknetConnections = new CopyOnWriteArrayList<>();

switch ( event.getType() ) {
            case NEW_INCOMING_CONNECTION:
                this.raknetConnections.add( event.getConnection() );
                break;
}
```
In some ticker method:
```java
for ( Connection con : this.raknetConnections ) {
    EncapsulatedPacket packetData;
        while ( ( packetData = con.receive() ) != null ) {
            PacketBuffer buffer = new PacketBuffer( packetData.getPacketData(), 0 )
            // Handle your custom data here
        }
}
```
The only things this lib does not handle is security at any point. Password support could be built in if needed but for the encryption parts in Raknet it is likely to not happen since there is no proper Java port of libcat. If you don't enable raknet encryption you should be fine in all cases.

**Comment by shuizhihun** [comment]
Thank you very much!
